interface types {
    use jabratech:common/types.{currency};

    record request{
        currency: currency,
        alpha: f64,
        rho: f64,
        nu: f64,
        three-delta-points: list<f64>
    }

    record smile{
        expiry: string,
        name: string,
        smile: f64,
        adj: f64,
        final-value: f64
    }

    record smile-response{
        code: s16,
        message: string,
        data: list<smile>,
    }

}